name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux_tests:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.4', '8.5']

    name: PHP ${{ matrix.php }} - Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          coverage: xdebug

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-stable'

      - name: Execute tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: vendor/bin/phpunit --display-deprecation

  windows_tests:
    runs-on: windows-2022
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      fail-fast: true
      matrix:
        php: ['8.4', '8.5']

    name: PHP ${{ matrix.php }} - Windows

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: '--prefer-stable --ignore-platform-req=ext-posix'

      - name: Set PHPUnit
        shell: bash
        run: vendor/bin/phpunit --version

      - name: Execute tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: vendor/bin/phpunit --no-coverage
